[tool.poetry]
package-mode = false

[tool.poetry.dependencies]
python = "~3.12"
numpy = "^2.1.2"
polars = "^1.10.0"
ipykernel = "^6.29.5"
matplotlib = "^3.9.2"
seaborn = "^0.13.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
